/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as CandidatIdRouteImport } from './routes/candidat/$id'
import { Route as RecuIndexRouteImport } from './routes/recu/index'
import { Route as RecuCodeRouteImport } from './routes/recu/$code'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminReconcileRouteImport } from './routes/api/admin/reconcile'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminVotesRouteImport } from './routes/api/admin/votes'
import { Route as ApiCandidatesIndexRouteImport } from './routes/api/candidates/index'
import { Route as ApiCandidatesIdRouteImport } from './routes/api/candidates.$id'
import { Route as ApiCronReconcileRouteImport } from './routes/api/cron/reconcile'
import { Route as ApiPaymentCountriesRouteImport } from './routes/api/payment/countries'
import { Route as ApiPaymentOperatorsRouteImport } from './routes/api/payment/operators'
import { Route as ApiPhotosIdRouteImport } from './routes/api/photos.$id'
import { Route as ApiReceiptsCodeRouteImport } from './routes/api/receipts.$code'
import { Route as ApiSettingsPublicRouteImport } from './routes/api/settings/public'
import { Route as ApiVotesIndexRouteImport } from './routes/api/votes/index'
import { Route as ApiVotesWebhookRouteImport } from './routes/api/votes/webhook'
import { Route as ApiAdminCandidatesIndexRouteImport } from './routes/api/admin/candidates/index'
import { Route as ApiAdminCandidatesIdRouteImport } from './routes/api/admin/candidates.$id'
import { Route as ApiAdminPhotosIndexRouteImport } from './routes/api/admin/photos/index'
import { Route as ApiAdminPhotosIdRouteImport } from './routes/api/admin/photos.$id'
import { Route as ApiVotesIdStatusRouteImport } from './routes/api/votes.$id.status'
import { Route as ApiAdminCandidatesIdPhotosRouteImport } from './routes/api/admin/candidates.$id.photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatIdRoute = CandidatIdRouteImport.update({
  id: '/candidat/$id',
  path: '/candidat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuIndexRoute = RecuIndexRouteImport.update({
  id: '/recu/',
  path: '/recu/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuCodeRoute = RecuCodeRouteImport.update({
  id: '/recu/$code',
  path: '/recu/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReconcileRoute = ApiAdminReconcileRouteImport.update({
  id: '/api/admin/reconcile',
  path: '/api/admin/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVotesRoute = ApiAdminVotesRouteImport.update({
  id: '/api/admin/votes',
  path: '/api/admin/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidatesIndexRoute = ApiCandidatesIndexRouteImport.update({
  id: '/api/candidates/',
  path: '/api/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandidatesIdRoute = ApiCandidatesIdRouteImport.update({
  id: '/api/candidates/$id',
  path: '/api/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReconcileRoute = ApiCronReconcileRouteImport.update({
  id: '/api/cron/reconcile',
  path: '/api/cron/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCountriesRoute = ApiPaymentCountriesRouteImport.update({
  id: '/api/payment/countries',
  path: '/api/payment/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentOperatorsRoute = ApiPaymentOperatorsRouteImport.update({
  id: '/api/payment/operators',
  path: '/api/payment/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosIdRoute = ApiPhotosIdRouteImport.update({
  id: '/api/photos/$id',
  path: '/api/photos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsCodeRoute = ApiReceiptsCodeRouteImport.update({
  id: '/api/receipts/$code',
  path: '/api/receipts/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsPublicRoute = ApiSettingsPublicRouteImport.update({
  id: '/api/settings/public',
  path: '/api/settings/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotesIndexRoute = ApiVotesIndexRouteImport.update({
  id: '/api/votes/',
  path: '/api/votes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotesWebhookRoute = ApiVotesWebhookRouteImport.update({
  id: '/api/votes/webhook',
  path: '/api/votes/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCandidatesIndexRoute = ApiAdminCandidatesIndexRouteImport.update({
  id: '/api/admin/candidates/',
  path: '/api/admin/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCandidatesIdRoute = ApiAdminCandidatesIdRouteImport.update({
  id: '/api/admin/candidates/$id',
  path: '/api/admin/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPhotosIndexRoute = ApiAdminPhotosIndexRouteImport.update({
  id: '/api/admin/photos/',
  path: '/api/admin/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPhotosIdRoute = ApiAdminPhotosIdRouteImport.update({
  id: '/api/admin/photos/$id',
  path: '/api/admin/photos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotesIdStatusRoute = ApiVotesIdStatusRouteImport.update({
  id: '/api/votes/$id/status',
  path: '/api/votes/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCandidatesIdPhotosRoute =
  ApiAdminCandidatesIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => ApiAdminCandidatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/api/health': typeof ApiHealthRoute
  '/candidat/$id': typeof CandidatIdRoute
  '/recu/$code': typeof RecuCodeRoute
  '/recu/': typeof RecuIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/reconcile': typeof ApiAdminReconcileRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/votes': typeof ApiAdminVotesRoute
  '/api/candidates/$id': typeof ApiCandidatesIdRoute
  '/api/cron/reconcile': typeof ApiCronReconcileRoute
  '/api/payment/countries': typeof ApiPaymentCountriesRoute
  '/api/payment/operators': typeof ApiPaymentOperatorsRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
  '/api/receipts/$code': typeof ApiReceiptsCodeRoute
  '/api/settings/public': typeof ApiSettingsPublicRoute
  '/api/votes/webhook': typeof ApiVotesWebhookRoute
  '/api/candidates/': typeof ApiCandidatesIndexRoute
  '/api/votes/': typeof ApiVotesIndexRoute
  '/api/admin/candidates/$id': typeof ApiAdminCandidatesIdRouteWithChildren
  '/api/admin/photos/$id': typeof ApiAdminPhotosIdRoute
  '/api/votes/$id/status': typeof ApiVotesIdStatusRoute
  '/api/admin/candidates/': typeof ApiAdminCandidatesIndexRoute
  '/api/admin/photos/': typeof ApiAdminPhotosIndexRoute
  '/api/admin/candidates/$id/photos': typeof ApiAdminCandidatesIdPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/api/health': typeof ApiHealthRoute
  '/candidat/$id': typeof CandidatIdRoute
  '/recu/$code': typeof RecuCodeRoute
  '/recu': typeof RecuIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/reconcile': typeof ApiAdminReconcileRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/votes': typeof ApiAdminVotesRoute
  '/api/candidates/$id': typeof ApiCandidatesIdRoute
  '/api/cron/reconcile': typeof ApiCronReconcileRoute
  '/api/payment/countries': typeof ApiPaymentCountriesRoute
  '/api/payment/operators': typeof ApiPaymentOperatorsRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
  '/api/receipts/$code': typeof ApiReceiptsCodeRoute
  '/api/settings/public': typeof ApiSettingsPublicRoute
  '/api/votes/webhook': typeof ApiVotesWebhookRoute
  '/api/candidates': typeof ApiCandidatesIndexRoute
  '/api/votes': typeof ApiVotesIndexRoute
  '/api/admin/candidates/$id': typeof ApiAdminCandidatesIdRouteWithChildren
  '/api/admin/photos/$id': typeof ApiAdminPhotosIdRoute
  '/api/votes/$id/status': typeof ApiVotesIdStatusRoute
  '/api/admin/candidates': typeof ApiAdminCandidatesIndexRoute
  '/api/admin/photos': typeof ApiAdminPhotosIndexRoute
  '/api/admin/candidates/$id/photos': typeof ApiAdminCandidatesIdPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/api/health': typeof ApiHealthRoute
  '/candidat/$id': typeof CandidatIdRoute
  '/recu/$code': typeof RecuCodeRoute
  '/recu/': typeof RecuIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/reconcile': typeof ApiAdminReconcileRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/votes': typeof ApiAdminVotesRoute
  '/api/candidates/$id': typeof ApiCandidatesIdRoute
  '/api/cron/reconcile': typeof ApiCronReconcileRoute
  '/api/payment/countries': typeof ApiPaymentCountriesRoute
  '/api/payment/operators': typeof ApiPaymentOperatorsRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
  '/api/receipts/$code': typeof ApiReceiptsCodeRoute
  '/api/settings/public': typeof ApiSettingsPublicRoute
  '/api/votes/webhook': typeof ApiVotesWebhookRoute
  '/api/candidates/': typeof ApiCandidatesIndexRoute
  '/api/votes/': typeof ApiVotesIndexRoute
  '/api/admin/candidates/$id': typeof ApiAdminCandidatesIdRouteWithChildren
  '/api/admin/photos/$id': typeof ApiAdminPhotosIdRoute
  '/api/votes/$id/status': typeof ApiVotesIdStatusRoute
  '/api/admin/candidates/': typeof ApiAdminCandidatesIndexRoute
  '/api/admin/photos/': typeof ApiAdminPhotosIndexRoute
  '/api/admin/candidates/$id/photos': typeof ApiAdminCandidatesIdPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/api/health'
    | '/candidat/$id'
    | '/recu/$code'
    | '/recu/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/reconcile'
    | '/api/admin/stats'
    | '/api/admin/votes'
    | '/api/candidates/$id'
    | '/api/cron/reconcile'
    | '/api/payment/countries'
    | '/api/payment/operators'
    | '/api/photos/$id'
    | '/api/receipts/$code'
    | '/api/settings/public'
    | '/api/votes/webhook'
    | '/api/candidates/'
    | '/api/votes/'
    | '/api/admin/candidates/$id'
    | '/api/admin/photos/$id'
    | '/api/votes/$id/status'
    | '/api/admin/candidates/'
    | '/api/admin/photos/'
    | '/api/admin/candidates/$id/photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/api/health'
    | '/candidat/$id'
    | '/recu/$code'
    | '/recu'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/reconcile'
    | '/api/admin/stats'
    | '/api/admin/votes'
    | '/api/candidates/$id'
    | '/api/cron/reconcile'
    | '/api/payment/countries'
    | '/api/payment/operators'
    | '/api/photos/$id'
    | '/api/receipts/$code'
    | '/api/settings/public'
    | '/api/votes/webhook'
    | '/api/candidates'
    | '/api/votes'
    | '/api/admin/candidates/$id'
    | '/api/admin/photos/$id'
    | '/api/votes/$id/status'
    | '/api/admin/candidates'
    | '/api/admin/photos'
    | '/api/admin/candidates/$id/photos'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/api/health'
    | '/candidat/$id'
    | '/recu/$code'
    | '/recu/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/reconcile'
    | '/api/admin/stats'
    | '/api/admin/votes'
    | '/api/candidates/$id'
    | '/api/cron/reconcile'
    | '/api/payment/countries'
    | '/api/payment/operators'
    | '/api/photos/$id'
    | '/api/receipts/$code'
    | '/api/settings/public'
    | '/api/votes/webhook'
    | '/api/candidates/'
    | '/api/votes/'
    | '/api/admin/candidates/$id'
    | '/api/admin/photos/$id'
    | '/api/votes/$id/status'
    | '/api/admin/candidates/'
    | '/api/admin/photos/'
    | '/api/admin/candidates/$id/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CandidatIdRoute: typeof CandidatIdRoute
  RecuCodeRoute: typeof RecuCodeRoute
  RecuIndexRoute: typeof RecuIndexRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminReconcileRoute: typeof ApiAdminReconcileRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminVotesRoute: typeof ApiAdminVotesRoute
  ApiCandidatesIdRoute: typeof ApiCandidatesIdRoute
  ApiCronReconcileRoute: typeof ApiCronReconcileRoute
  ApiPaymentCountriesRoute: typeof ApiPaymentCountriesRoute
  ApiPaymentOperatorsRoute: typeof ApiPaymentOperatorsRoute
  ApiPhotosIdRoute: typeof ApiPhotosIdRoute
  ApiReceiptsCodeRoute: typeof ApiReceiptsCodeRoute
  ApiSettingsPublicRoute: typeof ApiSettingsPublicRoute
  ApiVotesWebhookRoute: typeof ApiVotesWebhookRoute
  ApiCandidatesIndexRoute: typeof ApiCandidatesIndexRoute
  ApiVotesIndexRoute: typeof ApiVotesIndexRoute
  ApiAdminCandidatesIdRoute: typeof ApiAdminCandidatesIdRouteWithChildren
  ApiAdminPhotosIdRoute: typeof ApiAdminPhotosIdRoute
  ApiVotesIdStatusRoute: typeof ApiVotesIdStatusRoute
  ApiAdminCandidatesIndexRoute: typeof ApiAdminCandidatesIndexRoute
  ApiAdminPhotosIndexRoute: typeof ApiAdminPhotosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidat/$id': {
      id: '/candidat/$id'
      path: '/candidat/$id'
      fullPath: '/candidat/$id'
      preLoaderRoute: typeof CandidatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recu/': {
      id: '/recu/'
      path: '/recu'
      fullPath: '/recu/'
      preLoaderRoute: typeof RecuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recu/$code': {
      id: '/recu/$code'
      path: '/recu/$code'
      fullPath: '/recu/$code'
      preLoaderRoute: typeof RecuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reconcile': {
      id: '/api/admin/reconcile'
      path: '/api/admin/reconcile'
      fullPath: '/api/admin/reconcile'
      preLoaderRoute: typeof ApiAdminReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/votes': {
      id: '/api/admin/votes'
      path: '/api/admin/votes'
      fullPath: '/api/admin/votes'
      preLoaderRoute: typeof ApiAdminVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidates/': {
      id: '/api/candidates/'
      path: '/api/candidates'
      fullPath: '/api/candidates/'
      preLoaderRoute: typeof ApiCandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candidates/$id': {
      id: '/api/candidates/$id'
      path: '/api/candidates/$id'
      fullPath: '/api/candidates/$id'
      preLoaderRoute: typeof ApiCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reconcile': {
      id: '/api/cron/reconcile'
      path: '/api/cron/reconcile'
      fullPath: '/api/cron/reconcile'
      preLoaderRoute: typeof ApiCronReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/countries': {
      id: '/api/payment/countries'
      path: '/api/payment/countries'
      fullPath: '/api/payment/countries'
      preLoaderRoute: typeof ApiPaymentCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/operators': {
      id: '/api/payment/operators'
      path: '/api/payment/operators'
      fullPath: '/api/payment/operators'
      preLoaderRoute: typeof ApiPaymentOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos/$id': {
      id: '/api/photos/$id'
      path: '/api/photos/$id'
      fullPath: '/api/photos/$id'
      preLoaderRoute: typeof ApiPhotosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$code': {
      id: '/api/receipts/$code'
      path: '/api/receipts/$code'
      fullPath: '/api/receipts/$code'
      preLoaderRoute: typeof ApiReceiptsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/public': {
      id: '/api/settings/public'
      path: '/api/settings/public'
      fullPath: '/api/settings/public'
      preLoaderRoute: typeof ApiSettingsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/votes/': {
      id: '/api/votes/'
      path: '/api/votes'
      fullPath: '/api/votes/'
      preLoaderRoute: typeof ApiVotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/votes/webhook': {
      id: '/api/votes/webhook'
      path: '/api/votes/webhook'
      fullPath: '/api/votes/webhook'
      preLoaderRoute: typeof ApiVotesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/candidates/': {
      id: '/api/admin/candidates/'
      path: '/api/admin/candidates'
      fullPath: '/api/admin/candidates/'
      preLoaderRoute: typeof ApiAdminCandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/candidates/$id': {
      id: '/api/admin/candidates/$id'
      path: '/api/admin/candidates/$id'
      fullPath: '/api/admin/candidates/$id'
      preLoaderRoute: typeof ApiAdminCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/photos/': {
      id: '/api/admin/photos/'
      path: '/api/admin/photos'
      fullPath: '/api/admin/photos/'
      preLoaderRoute: typeof ApiAdminPhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/photos/$id': {
      id: '/api/admin/photos/$id'
      path: '/api/admin/photos/$id'
      fullPath: '/api/admin/photos/$id'
      preLoaderRoute: typeof ApiAdminPhotosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/votes/$id/status': {
      id: '/api/votes/$id/status'
      path: '/api/votes/$id/status'
      fullPath: '/api/votes/$id/status'
      preLoaderRoute: typeof ApiVotesIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/candidates/$id/photos': {
      id: '/api/admin/candidates/$id/photos'
      path: '/photos'
      fullPath: '/api/admin/candidates/$id/photos'
      preLoaderRoute: typeof ApiAdminCandidatesIdPhotosRouteImport
      parentRoute: typeof ApiAdminCandidatesIdRoute
    }
  }
}

interface ApiAdminCandidatesIdRouteChildren {
  ApiAdminCandidatesIdPhotosRoute: typeof ApiAdminCandidatesIdPhotosRoute
}

const ApiAdminCandidatesIdRouteChildren: ApiAdminCandidatesIdRouteChildren = {
  ApiAdminCandidatesIdPhotosRoute: ApiAdminCandidatesIdPhotosRoute,
}

const ApiAdminCandidatesIdRouteWithChildren =
  ApiAdminCandidatesIdRoute._addFileChildren(ApiAdminCandidatesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ApiHealthRoute: ApiHealthRoute,
  CandidatIdRoute: CandidatIdRoute,
  RecuCodeRoute: RecuCodeRoute,
  RecuIndexRoute: RecuIndexRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminReconcileRoute: ApiAdminReconcileRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminVotesRoute: ApiAdminVotesRoute,
  ApiCandidatesIdRoute: ApiCandidatesIdRoute,
  ApiCronReconcileRoute: ApiCronReconcileRoute,
  ApiPaymentCountriesRoute: ApiPaymentCountriesRoute,
  ApiPaymentOperatorsRoute: ApiPaymentOperatorsRoute,
  ApiPhotosIdRoute: ApiPhotosIdRoute,
  ApiReceiptsCodeRoute: ApiReceiptsCodeRoute,
  ApiSettingsPublicRoute: ApiSettingsPublicRoute,
  ApiVotesWebhookRoute: ApiVotesWebhookRoute,
  ApiCandidatesIndexRoute: ApiCandidatesIndexRoute,
  ApiVotesIndexRoute: ApiVotesIndexRoute,
  ApiAdminCandidatesIdRoute: ApiAdminCandidatesIdRouteWithChildren,
  ApiAdminPhotosIdRoute: ApiAdminPhotosIdRoute,
  ApiVotesIdStatusRoute: ApiVotesIdStatusRoute,
  ApiAdminCandidatesIndexRoute: ApiAdminCandidatesIndexRoute,
  ApiAdminPhotosIndexRoute: ApiAdminPhotosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
